version: '3.0'

services:
  my-api_db:
    image: postgres:14.1-alpine
    container_name: my-api_db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./my-api_db:/my-api_db/data
    networks:
      - my-api-network

  my-api:
    container_name: my-api
    build:
      context: .
    ports:
      - "${PORT}:${OUTSIDE_PORT}"
    depends_on:
      - my-api_db
    expose:
      - ${PORT}
    restart: on-failure
    volumes:
      - ./src:/my-api/src
      - ./nodemon.json:/my-api/nodemon.json
      - ./logs:/logs
    networks:
      - my-api-network

networks:
  my-api-network:
    driver: bridge